spring.application.name=skylink-backend

# bind our custom datasource props (values come from env or external file)
app.datasource.url=${APP_DATASOURCE_URL:}
app.datasource.username=${APP_DATASOURCE_USERNAME:}
app.datasource.password=${APP_DATASOURCE_PASSWORD:}
app.jwt.secret=${JWT_SECRET}

# JPA / Hibernate (safe to keep in repo)
spring.jpa.hibernate.ddl-auto=validate
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# WeatherAPI
app.weather.api.key=${WEATHER_API_KEY:}
app.weather.api.base-url=https://api.weatherapi.com/v1